/**
 * Built-in safety extension for pi when running under ACP (e.g. Zed).
 *
 * Prevents tools (especially `bash`) from hanging indefinitely by:
 * 1. Guiding the LLM in system prompt about streaming/SSE commands.
 * 2. Intercepting dangerous deadlock patterns (e.g. `curl -H "Accept: text/event-stream" ... | head`).
 * 3. Enforcing a sensible default timeout on all bash commands (60s) if the LLM didn't specify one.
 */

interface ToolCallEvent {
  toolName: string
  toolCallId?: string
  input: Record<string, unknown>
}

interface BeforeAgentStartEvent {
  systemPrompt: string
  prompt: string
}

interface ExtensionAPI {
  on(event: 'before_agent_start', handler: (event: BeforeAgentStartEvent) => Promise<{ systemPrompt?: string } | void> | { systemPrompt?: string } | void): void
  on(event: 'tool_call', handler: (event: ToolCallEvent) => Promise<{ block?: boolean; reason?: string } | void> | { block?: boolean; reason?: string } | void): void
  on(event: string, handler: (event: any, ctx?: any) => Promise<any> | any): void
}

export default function bashGuardExtension(pi: ExtensionAPI): void {
  // 1. Proactive guidance in system prompt to minimize bad commands generated by the LLM
  pi.on('before_agent_start', async event => {
    const safetyNotice = `
\n## Terminal & Streaming Safety Guidelines
- When inspecting or probing streaming / SSE / MCP endpoints (e.g. headers with \`Accept: text/event-stream\`), NEVER pipe directly into \`head\` without an explicit timeout (\`-m <seconds>\`). SSE connections stay open indefinitely, so piping to \`head\` will hang the session.
- Always add \`-m 3\` (or another finite timeout) and \`-N\` (\`--no-buffer\`) to \`curl\` commands when contacting streaming or unknown endpoints.
`
    return {
      systemPrompt: `${event.systemPrompt}\n${safetyNotice}`
    }
  })

  // 2. Intercept and prevent hanging bash calls
  pi.on('tool_call', async event => {
    if (event.toolName === 'bash') {
      const input = event.input as { command?: string; timeout?: number }
      const cmd = typeof input.command === 'string' ? input.command : ''

      // Detect lethal deadlock pattern: streaming response piped into head without timeout
      const isStreaming = /text\/event-stream|stream/i.test(cmd)
      const hasHeadPipe = /\|\s*head(\s+|$)/i.test(cmd)
      const hasCurlTimeout = /-m\s+\d+|--max-time\s+\d+/i.test(cmd)

      if (isStreaming && hasHeadPipe && !hasCurlTimeout) {
        return {
          block: true,
          reason:
            'Blocked potentially hanging command: Piping a streaming/SSE response into `head` without an explicit timeout will hang indefinitely. Please add `-m 3` and `-N` to your curl command, or provide an explicit `timeout` parameter.'
        }
      }

      // Default timeout safeguard: enforce 60s timeout if model didn't specify one
      if (input.timeout === undefined || input.timeout <= 0) {
        input.timeout = 60
      }
    }
  })
}
